#pragma once
#include "VMProtectSDK.h"

#define ENTITY_LIST_INTERFACE_S		"VClientEntityList003"
#define ENGINE_CLIENT_INTERFACE_S	"VEngineClient014"

#ifdef NDEBUG
#define ENTITY_LIST_INTERFACE		VMProtectDecryptStringA(ENTITY_LIST_INTERFACE_S)
#define ENGINE_CLIENT_INTERFACE		VMProtectDecryptStringA(ENGINE_CLIENT_INTERFACE_S)
#else
#define ENTITY_LIST_INTERFACE		ENTITY_LIST_INTERFACE_S
#define ENGINE_CLIENT_INTERFACE		ENGINE_CLIENT_INTERFACE_S
#endif
