#pragma once

//Init cheat code
#define IO_INIT_CHEAT_DATA				CTL_CODE(FILE_DEVICE_UNKNOWN, 0x6000, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
#define IO_DRIVER_ALIVE     			CTL_CODE(FILE_DEVICE_UNKNOWN, 0x6001, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
#define IO_GET_DRIVER_STATUS			CTL_CODE(FILE_DEVICE_UNKNOWN, 0x6002, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)

//Cheat Memory access
#define IO_READ_PROCESS_MEMORY			CTL_CODE(FILE_DEVICE_UNKNOWN, 0x6003, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
#define IO_WRITE_PROCESS_MEMORY			CTL_CODE(FILE_DEVICE_UNKNOWN, 0x6004, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
#define IO_READ_PROCESS_MEMORY_32		CTL_CODE(FILE_DEVICE_UNKNOWN, 0x6005, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
#define IO_WRITE_PROCESS_MEMORY_32		CTL_CODE(FILE_DEVICE_UNKNOWN, 0x6006, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)

//Injection Functions (for internal cheats)
#define IO_INJECT_DLL					CTL_CODE(FILE_DEVICE_UNKNOWN, 0x6007, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)

//CS GO ONLY Methods
#define IO_GET_ALL_MODULES				CTL_CODE(FILE_DEVICE_UNKNOWN, 0x6008, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)


typedef struct _KERNEL_INIT_DATA_REQUEST
{
	DWORD64 CsgoId;
	DWORD64 CheatId;
	NTSTATUS Result;
} KERNEL_INIT_DATA_REQUEST, * PKERNEL_INIT_DATA_REQUEST;

typedef struct _KERNEL_READ_REQUEST
{
	DWORD64 Address;
	DWORD64 Response;
	SIZE_T Size;
	NTSTATUS Result;
} KERNEL_READ_REQUEST, * PKERNEL_READ_REQUEST;

typedef struct _KERNEL_WRITE_REQUEST
{
	DWORD64 Address;
	DWORD64 Value;
	SIZE_T Size;
	NTSTATUS Result;
} KERNEL_WRITE_REQUEST, * PKERNEL_WRITE_REQUEST;

typedef struct _KERNEL_READ_REQUEST32
{
	DWORD32 Address;
	DWORD64 Response;
	SIZE_T Size;
	NTSTATUS Result;
} KERNEL_READ_REQUEST32, * PKERNEL_READ_REQUEST32;

typedef struct _KERNEL_WRITE_REQUEST32
{
	DWORD32 Address;
	DWORD64 Value;
	SIZE_T Size;
	NTSTATUS Result;
} KERNEL_WRITE_REQUEST32, * PKERNEL_WRITE_REQUEST32;


typedef struct _KERNEL_GET_MODULE
{
	DWORD64 ImageBase;
	SIZE_T ImageSize;
} KERNEL_GET_MODULE, * PKERNEL_GET_MODULE;

typedef struct _KERNEL_GET_MODULE32
{
	DWORD32 ImageBase;
	SIZE_T ImageSize;
} KERNEL_GET_MODULE32, * PKERNEL_GET_MODULE32;


typedef struct _KERNEL_GET_CSGO_MODULES
{
	DWORD32 bClient;
	DWORD32 bEngine;
	DWORD32 bServer;
	NTSTATUS result;
} KERNEL_GET_CSGO_MODULES, * PKERNEL_GET_CSGO_MODULES;


typedef struct _DRIVER_ALIVE_REQUEST
{
	NTSTATUS status;
} DRIVER_ALIVE_REQUEST, * PDRIVER_ALIVE_REQUEST;

typedef struct _DRIVER_STATUS_REQUEST
{
	NTSTATUS result;
	BOOLEAN bbInited;
	BOOLEAN driverInited;
} DRIVER_STATUS_REQUEST, *PDRIVER_STATUS_REQUEST;
